name: "🚀 Feature request"
description: Suggest a feature that will improve Vueform Builder
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition to Vueform Builder, including the possible use cases and alternatives you have considered. If you have a working prototype that implements it, please include a link.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: Check existing [issues](https://github.com/vueform/builder/issues) and [ideas](https://github.com/vueform/builder/discussions/categories/ideas).
          required: true